# Generated by Django 5.1.6 on 2026-02-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderId',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='productId',
        ),
    ]
