# Generated by Django 5.2.4 on 2026-03-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_order_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
