# Generated by Django 5.1.6 on 2026-02-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbysize',
            old_name='product',
            new_name='productId',
        ),
    ]
