# Generated by Django 6.0.2 on 2026-05-04 14:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'precio'], name='prod_activo_precio_idx'),
        ),
        migrations.AddIndex(
            model_name='stockportalla',
            index=models.Index(fields=['producto', 'talla'], name='stock_producto_talla_idx'),
        ),
    ]
